language: rust

git:
  submodules: false

cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
 
env:
  global:
    - RUSTFLAGS="-C target-feature=+aes,+sse,+sse2"

matrix:
  fast_finish: true

  allow_failures:
    - rust: nightly

  include:
    - name: "format check: rustfmt"
      rust: stable
      install: true
      script: |
        if rustup component add rustfmt-preview ; then
            ci/run_cargo_tool.sh check_fmt || true
        fi
    - name: "style check: clippy"
      if: env(ENABLE_CLIPPY) = 1
      install: true
      script: |
        if rustup component add clippy-preview ; then
            ci/run_cargo_tool.sh clippy
        fi

before_cache:
  - rm -rf "$HOME/.cargo/registry/src"
  - chmod -R a+r $HOME/.cargo;

before_install: bash ci/prepare_install.sh

install: bash ci/install.sh

before_script: ci/prepare_build.sh dev

script: bash ci/build.sh dev

after_script: set +e

branches:
  only:
    - master

notifications:
  email:
    on_success: never