[build]
rustflags = [
    "-C", "target_cpu=native",
    "-C", "target-feature=+64bit,+aes,+avx,+avx2,+sse3"
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-feature=+64bit,+aes,+avx,+avx2,+sse3"
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=+64bit,+aes,+avx,+avx2,+sse3"
]

[profile.test]
opt-level = 0
lto = false
debug = 2
debug-assertions = true

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false
panic = 'abort'