[build]
rustflags = [
    "-C", "target-cpu=native", 
    "-C", "target-feature=+aes"
]

[profile.test]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false