[build]
rustflags = [
    "-C", "target-feature=+64bit,64bit-mode,+aes,+avx,+avx2,+fma,+x87"
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-feature=+64bit,64bit-mode,+aes,+avx,+avx2,+fma,+x87"
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-feature=+64bit,64bit-mode,+aes,+avx,+avx2,+fma,+x87"
]

[profile.test]
opt-level = 0
lto = false
debug = 2
debug-assertions = true

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false
panic = 'abort'