[build]
rustflags = [
    "-C", "target-feature=+aes,+sse,+sse2"
]

[profile.test]
opt-level = 0
lto = false
debug = 2
debug-assertions = true

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false
panic = 'abort'