[build]
rustflags = [
    "-C", "target-cpu=native", 
    "-C", "target-feature=+aes"
]

[profile.test]
opt-level = 0
lto = false
debug = true
debug-assertions = true

[profile.integrationtest]
opt-level = 0
lto = false
debug = false
debug-assertions = true

[profile.bench]
opt-level = 3
lto = true
debug = false
debug-assertions = false

[profile.release]
opt-level = 3
lto = true
debug = false
debug-assertions = false